contexts:
  - name: cluster1
    env:
      KUBE_CONTEXT: cluster1
      # REGION: us-east-2
  - name: cluster2
    env:
      KUBE_CONTEXT: cluster2

env:
  CLOUD: aws # supported clouds: aws, gcp
  REGION: us-east-1

volumes:
#  $HOME/.ssh: /root/.ssh
#  $HOME/.gitconfig: /root/.gitconfig
#  $HOME/.aws: /root/.aws
#  $HOME/.config/gh: /root/.config/gh
#  $HOME/.cfconfig: /root/.cfconfig
